# Generated by Django 4.2.18 on 2025-01-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('others', 'Others')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
